### ISSUE TITLE
Creación de estructura de la base de datos de la tablas parte 3

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#10]

**Comment by mgallegos** [comment]
Revisión:
- Utilizar issue #10 para los commit
- El nombre de la [tabla es ASSET_Period](https://github.com/mgallegos/decima-asset/blob/master/src/migrations/2016_08_24_225533_create_assets_tables_part_three.php#L33)
- La sintaxis del "small int" es ->smallInteger
- Agregar columna depreciation_concept en la tabla ASSET_Setting
- Agregar tabla de movimiento (Ya esta lista en el documento).

**Comment by mgallegos** [comment]
Tambien en la tabla ASSET_Period cambiar **_anio_** por **_year_**

**Comment by arcp** [comment]
ya hice los cambios en el script

**Comment by mgallegos** [comment]
Revisión:
- No especificar longitud del script [en la columna depreciation_concept](https://github.com/mgallegos/decima-asset/blob/master/src/migrations/2016_08_24_225533_create_assets_tables_part_three.php#L21)
- El nombre correcto de [la tabla es ASSET_Period](https://github.com/mgallegos/decima-asset/blob/master/src/migrations/2016_08_24_225533_create_assets_tables_part_three.php#L33)
- [El orden de los DROP](https://github.com/mgallegos/decima-asset/blob/master/src/migrations/2016_08_24_225533_create_assets_tables_part_three.php#L76-L78) deben hacerse en el orden inverso de creación de tablas.

**Comment by arcp** [comment]
corregido el script

**Comment by mgallegos** [comment]
Falto cambiar el nombre al final: https://github.com/mgallegos/decima-asset/blob/master/src/migrations/2016_08_24_225533_create_assets_tables_part_three.php#L77
