### ISSUE TITLE
Desarrollar pantalla de Gestión de Movimientos 

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#12]
Controlador: MovementManager.php

Repositorio: EloquentMovement.php

Servicio: MovementManager.php

Vista: movement-management.blade.php

Modelo: Movement.php

Prefijos: asset-mm-, assetMm, asset_mm

**Comment by JoseRamos92** [comment]
la vista se llamara movement-manager o movement-management???

**Comment by mgallegos** [comment]
Error de dedo,  movement-management.blade.php es lo correcto.

**Comment by mgallegos** [comment]
Para habilitar campos en base al tipo de movimiento:
- Agregar en el autocomplete de tipos de movimientos todos los campos que sean checkbox ([ver ejemplo](https://github.com/mgallegos/decima-inventory/blob/master/src/Mgallegos/DecimaInventory/Inventory/Services/MovementTypeManagement/MovementTypeManager.php#L209-L218)).
- Capturar el evento de seleccion de tipo de movimiento en el autocomplete y habilitar/deshabilitar campos en base al tipo seleccionado ([ver ejemplo](https://github.com/mgallegos/decima-inventory/blob/master/src/views/movement-management.blade.php#L506-L535)).

**Comment by mgallegos** [comment]
Para validación del tipo de movimiento, ver ejemplo para contar registros en una tabla:

https://github.com/mgallegos/decima-inventory/blob/master/src/views/movement-management.blade.php#L193-L196
