### ISSUE TITLE
Desarrollar pantalla de Gestión de Categorías

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#3]
Controlador: CategoryManager.php

Repositorio: EloquentCategory.php

Servicio: CategoryManager.php

Vista: category-management.blade.php

Modelo: Category.php

**Comment by mgallegos** [comment]
Implementar los siguientes 2 cambios ([ver documentación para más detalle](https://docs.google.com/document/d/1BEVRK2O-mKxWp9hyH29B2fAZ98VMksNtZvEucMBT5H4/edit#)):
- Completar el archivo de idiomas
- Completar la auditoría para los campos de autocomplete.
- En el grid se deben mostrar los nombres de las cuentas que faltan
- Se agregó la columna "Bienes depreciable" (agregar al script, agregar al grid, agregar al formulario)
- Se modificó el tipo de dato de la columna "Frecuencia de depreciación" (cambiar script, cambiar tipo en el formulario)

**Comment by mgallegos** [comment]
Ejemplo para implementación de auditoría de un autocomplete que se llena a partir de una tabla de la base (para el campo país):
- [Agregar el repositorio de la tabla (en este ejemplo AccountInterface) en el constructor](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/JournalManagement/JournalManager.php#L245) (no olvidar asignar variable y declarar el **_use_**)
- En el [service provider, pasar la clase al servicio](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/DecimaAccountingServiceProvider.php#L534).
- [Al momento de realizar la auditoria del campo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/JournalManagement/JournalManager.php#L819), utilizar el método byId($id) del repositorio para obtener la columna nombre (o la que corresponda según cada caso) y ese valor pasarlo al campo de auditoría correspondiente.

**Comment by mgallegos** [comment]
Pendientes al 25/08:
- Completar archivo de idioma y revisar organización.
- Bug de número de depreciación
- Arreglar la sangría en los scripts.
- Implementar auditoría de autocomplete

**Comment by mgallegos** [comment]
Otros pendientes:
- En el grid las columnas de Cuenta de depreciación y Cuenta de Gastos de depreciación no se muestran la llave concatenado con el nombre (la cuenta de activo fijo si se muestra correctamente).
- En la vista y en el grid corregir las lineas de archivo de idioma que no se habían colocado según el estándar (yo modifique el archivo de idiomas).
- El campo método de depreciación y frecuencia de depreciación es un campo requerido.
- Al hacer clic en editar los campos Cuenta de depreciación y Cuenta de Gastos nos se están llenando en el formulario.

**Comment by mgallegos** [comment]
En el siguiente enlace, te marque las lineas donde esta el error por el cual el campo Número de Depreciaciones siempre queda con valor cero:

https://github.com/mgallegos/decima-asset/blob/master/src/views/category-management.blade.php#L376-L377

Revísalo y me contas si identificas el problema.

**Comment by mgallegos** [comment]
Otro pendiente:
- El campo "Número de Depreciaciones" solo debe aceptar números enteros. Para lograr esto se debe agregar el atributo: data-mg-validator="positiveIntegerNoZero", esta validación tambien le da formato al número, agregandole una coma cuando se trata de miles, por lo que es necesario del lado servidor quitarle esa coma (ver siguiente punto).
- Para el campo "Número de Depreciaciones", es necesario agregarle la siguiente linea del lado del servidor para quitarle la coma al momento de agregar y editar: 
```php
$input['depreciations_total_number'] = str_replace(',', '', $input['depreciations_total_number']);
```

**Comment by arcp** [comment]
en el campo devuelve 0 porque falta agregar el id en el hidden

**Comment by arcp** [comment]
creo que ya termine :'D

**Comment by mgallegos** [comment]
Ejemplo de creación de función que devuelve los elementos de un autocomplete, crear en base a este ejemplo los de categoría:

https://github.com/mgallegos/decima-erp/blob/master/app/Kwaai/Template/Services/ModuleAppManagement/ModuleAppManager.php#L157
