### ISSUE TITLE
Desarrollar pantalla de Gestión de Tipo de Activo

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#5]
Controlador: AssetTypeManager.php

Repositorio: EloquentAssetType.php

Servicio: AssetTypeManager.php

Vista: asset-type-management.blade.php

Modelo: AssetType.php

**Comment by mgallegos** [comment]
No olvidar hacer un git pull dentro del core para actualizar la plantilla.

**Comment by arcp** [comment]
hice commit con mis cambios en el service provider
