### ISSUE TITLE
Desarrollar pantalla de Gestión de Activos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#6]
Controlador: AssetManager.php

Repositorio: EloquentAssetManager.php

Servicio: AssetManager.php

Vista: asset-manager.blade.php

Modelo: AssetManager.php

**Comment by mgallegos** [comment]
No olvidar hacer un git pull dentro del core para actualizar la plantilla.

**Comment by mgallegos** [comment]
Ejemplo campo de fecha:
https://github.com/mgallegos/decima-human-resources/blob/master/src/views/employee-management.blade.php#L404

**Comment by JoseRamos92** [comment]
que prefijos le pongo al asset-management.blade

**Comment by mgallegos** [comment]
Los podes ver en el archivo de diseño.

**Comment by mgallegos** [comment]
Pendientes:
- Completar editar y eliminar
- Implementar auditorías
- Completar el grid con todas las columnas

**Comment by JoseRamos92** [comment]
pongo todos las columnas en el grid

**Comment by mgallegos** [comment]
Si es necesario colocar todas las columnas en el grid, sin embargo las visibles son las siguientes:
- Nombre
- Departamento (cocarlo así en vez de Asignado a departamento, solo en el grid)
- Empleado
- Categoría
- Tipo de Activo
- Correlativo
- Código (asset_code)
- Estado

**Comment by JoseRamos92** [comment]
tengo un problema el grid no me muestra nada y ya revise y revise y no encuentro q estara mal

**Comment by JoseRamos92** [comment]
-ya funciona el eliminar
-el editar funciona parcialmente (mañana lo termino)
-Falta auditoria

**Comment by mgallegos** [comment]
Enterado, cualquier cosa me avisas.

**Comment by mgallegos** [comment]
Recursos:
- [Repositorio de departamento](https://github.com/mgallegos/decima-human-resources/blob/master/src/Mgallegos/DecimaHumanResources/DecimaHumanResourcesServiceProvider.php#L116)
- [Repositorio de empleado](https://github.com/mgallegos/decima-human-resources/blob/master/src/Mgallegos/DecimaHumanResources/DecimaHumanResourcesServiceProvider.php#L96)

**Comment by mgallegos** [comment]
Continuar con la creación del formulario de movimientos en la pestaña movimientos, se puede ver como [ejemplo el formulario de la pantalla Gestión de Libro Diario del módulo contable](https://github.com/mgallegos/decima-accounting/blob/master/src/views/journal-management.blade.php#L1325-L1409).
