### ISSUE TITLE
Desarrollar pantalla de Configuración Inicial de Activos Fijo

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#8]
Ver pantalla de ejemplo: Configuración contable inicial

Controlador: SettingManager.php

Repositorio: EloquentSetting.php

Servicio: SettingManager.php

Vista: Initial-fixed-asset-setup.blade.php

Modelo: Setting.php

**Comment by mgallegos** [comment]
Script de ejemplo para vista:

https://github.com/mgallegos/decima-accounting/blob/master/src/views/initial-accounting-setup.blade.php

**Comment by mgallegos** [comment]
Prefijos para la vista: inv-ifas-, InvIfas, inv_ifas_

**Comment by mgallegos** [comment]
Estudiar la lógica de la pantalla de contabilidad:
- [Ver controlador](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/SettingManager.php)
- [Ver servicio](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/SettingManagement/SettingManager.php)

**Comment by arcp** [comment]
acabo de crear el script de las tablas que me dijo que tenia que hacer
favor revisar.

**Comment by mgallegos** [comment]
Método para autocomplete de años: getYears()

Es necesario actualizar el core.

**Comment by mgallegos** [comment]
Al cargar la pantalla:
- Definir en el servicio un método que [devuelva la configuración actual](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/SettingManagement/SettingManager.php#L307).
- En el controlador pasar el arreglo [con la configuración actual](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/SettingManager.php#L73).
- En la vista, a cada campo asignarle como valor por defecto el que venga del arreglo de configuración actual, [ver ejemplo](https://github.com/mgallegos/decima-accounting/blob/master/src/views/initial-accounting-setup.blade.php#L82).

Al hacer clic en el botón actualizar:
- Para el año seleccionado crear un registro en la tabla periodo por cada mes (utilizar el servicio de periodos, podes ver el [ejemplo del servicio de contabilidad](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/SettingManagement/SettingManager.php#L421-L431), no va a ser igual pero se parece). 
- Hacer update en el resto de los campos de la tabla Setting.
- Hacer auditoría cuando se actualice los campos de la tabla Setting.

**Comment by mgallegos** [comment]
Sobre el journal:
- Definir el método del journal en el servicio
- Registrar el journal en journal.php
- Pasar los journal por medio del controlador a la vista.

**Comment by mgallegos** [comment]
Podes tomar de ejemplo estos archivos, para el autocomplete de centro de costos:
- https://github.com/mgallegos/decima-human-resources/blob/master/src/views/deparment-management.blade.php#L350-L351
- https://github.com/mgallegos/decima-human-resources/blob/master/src/Mgallegos/DecimaHumanResources/HumanResources/Controllers/DeparmentManager.php#L90
