### ISSUE TITLE
Crear repositorio y servicio de periodos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-asset#9]
Modelo: Period.php

Repositorio: EloquentPeriod.php

Servicio: PeriodManager.php

**Comment by mgallegos** [comment]
¿Cómo vas con esta parte?

**Comment by mgallegos** [comment]
¿Cómo vas con esta parte @arcp ?

**Comment by arcp** [comment]
Solo es de crear el servicio y el repositorio nada mas verdad??

**Comment by arcp** [comment]
Ahora la dejo de toque

**Comment by mgallegos** [comment]
Correcto, una vez creados, debes de mandarle como parámetro este servicio al servicio de SettingManager.
